import type { FormatAdapter } from '@/types'

export const asciidocAdapter: FormatAdapter = {
  id: 'asciidoc',
  snippets: [
    { id: 'bold', label: 'Bold', icon: 'Bold', template: '*${selection}${cursor}*', wrapSelection: true },
    { id: 'italic', label: 'Italic', icon: 'Italic', template: '_${selection}${cursor}_', wrapSelection: true },
    { id: 'underline', label: 'Underline', icon: 'Underline', template: '[.underline]#${selection}${cursor}#', wrapSelection: true },
    { id: 'code-inline', label: 'Inline Code', icon: 'Code', template: '`${selection}${cursor}`', wrapSelection: true },
    { id: 'code-block', label: 'Code Block', icon: 'FileCode', template: '[source,${cursor}]\n----\n${selection}\n----', wrapSelection: true },
    { id: 'heading1', label: 'Heading 1', template: '= ${selection}${cursor}', wrapSelection: true },
    { id: 'heading2', label: 'Heading 2', template: '== ${selection}${cursor}', wrapSelection: true },
    { id: 'heading3', label: 'Heading 3', template: '=== ${selection}${cursor}', wrapSelection: true },
    { id: 'link', label: 'Link', icon: 'Link', template: 'link:${cursor}[${selection}]', wrapSelection: true },
    { id: 'image', label: 'Image', icon: 'Image', template: 'image::${cursor}[]', wrapSelection: false },
    { id: 'list-bullet', label: 'Bullet List', template: '* ${selection}${cursor}', wrapSelection: true },
    { id: 'list-numbered', label: 'Numbered List', template: '. ${selection}${cursor}', wrapSelection: true },
    { id: 'math-inline', label: 'Inline Math', template: 'latexmath:[${selection}${cursor}]', wrapSelection: true },
    { id: 'math-block', label: 'Display Math', template: '[stem]\n++++\n${selection}${cursor}\n++++', wrapSelection: true },
    { id: 'blockquote', label: 'Quote', icon: 'Quote', template: '[quote]\n____\n${selection}${cursor}\n____', wrapSelection: true },
    { id: 'table', label: 'Table', icon: 'Table', template: '|===\n| ${cursor} | \n\n| | \n|===', wrapSelection: false },
    { id: 'comment', label: 'Comment', icon: 'MessageSquare', template: '// ${selection}${cursor}', wrapSelection: true },
    { id: 'hr', label: 'Horizontal Rule', icon: 'Minus', template: "'''", wrapSelection: false },
    { id: 'footnote', label: 'Footnote', template: 'footnote:[${selection}${cursor}]', wrapSelection: true },
    { id: 'label', label: 'Anchor', template: '[[${cursor}]]', wrapSelection: false },
    { id: 'ref', label: 'Cross Reference', template: '<<${cursor}>>', wrapSelection: false },
  ],
  toolbar: [
    'bold',
    'italic',
    'code-inline',
    { id: 'headings', label: 'Headings', icon: 'Heading', snippetIds: ['heading1', 'heading2', 'heading3'] },
    'link',
    'image',
    { id: 'lists', label: 'Lists', icon: 'List', snippetIds: ['list-bullet', 'list-numbered'] },
    { id: 'math', label: 'Math', icon: 'Sigma', snippetIds: ['math-inline', 'math-block'] },
    'underline',
    'code-block',
    'blockquote',
    'table',
    'comment',
    'hr',
    'footnote',
    'label',
    'ref',
  ],
}
