import type { FormatAdapter } from '@/types'

export const latexAdapter: FormatAdapter = {
  id: 'latex',
  snippets: [
    { id: 'bold', label: 'Bold', icon: 'Bold', template: '\\textbf{${selection}${cursor}}', wrapSelection: true },
    { id: 'italic', label: 'Italic', icon: 'Italic', template: '\\textit{${selection}${cursor}}', wrapSelection: true },
    { id: 'underline', label: 'Underline', icon: 'Underline', template: '\\underline{${selection}${cursor}}', wrapSelection: true },
    { id: 'code-inline', label: 'Inline Code', icon: 'Code', template: '\\texttt{${selection}${cursor}}', wrapSelection: true },
    { id: 'code-block', label: 'Code Block', icon: 'FileCode', template: '\\begin{verbatim}\n${selection}${cursor}\n\\end{verbatim}', wrapSelection: true },
    { id: 'heading1', label: 'Section', template: '\\section{${selection}${cursor}}', wrapSelection: true },
    { id: 'heading2', label: 'Subsection', template: '\\subsection{${selection}${cursor}}', wrapSelection: true },
    { id: 'heading3', label: 'Subsubsection', template: '\\subsubsection{${selection}${cursor}}', wrapSelection: true },
    { id: 'link', label: 'Link', icon: 'Link', template: '\\href{${cursor}}{${selection}}', wrapSelection: true },
    { id: 'image', label: 'Image', icon: 'Image', template: '\\includegraphics{${cursor}}', wrapSelection: false },
    { id: 'list-bullet', label: 'Bullet List', template: '\\begin{itemize}\n  \\item ${selection}${cursor}\n\\end{itemize}', wrapSelection: true },
    { id: 'list-numbered', label: 'Numbered List', template: '\\begin{enumerate}\n  \\item ${selection}${cursor}\n\\end{enumerate}', wrapSelection: true },
    { id: 'math-inline', label: 'Inline Math', template: '$${selection}${cursor}$', wrapSelection: true },
    { id: 'math-block', label: 'Display Math', template: '\\[\n${selection}${cursor}\n\\]', wrapSelection: true },
    { id: 'blockquote', label: 'Quote', icon: 'Quote', template: '\\begin{quote}\n${selection}${cursor}\n\\end{quote}', wrapSelection: true },
    { id: 'table', label: 'Table', icon: 'Table', template: '\\begin{tabular}{${cursor}}\n  \n\\end{tabular}', wrapSelection: false },
    { id: 'comment', label: 'Comment', icon: 'MessageSquare', template: '% ${selection}${cursor}', wrapSelection: true },
    { id: 'hr', label: 'Horizontal Rule', icon: 'Minus', template: '\\hrule', wrapSelection: false },
    { id: 'footnote', label: 'Footnote', template: '\\footnote{${selection}${cursor}}', wrapSelection: true },
    { id: 'label', label: 'Label', template: '\\label{${cursor}}', wrapSelection: false },
    { id: 'ref', label: 'Reference', template: '\\ref{${cursor}}', wrapSelection: false },
  ],
  toolbar: [
    'bold',
    'italic',
    'code-inline',
    { id: 'headings', label: 'Headings', icon: 'Heading', snippetIds: ['heading1', 'heading2', 'heading3'] },
    'link',
    'image',
    { id: 'lists', label: 'Lists', icon: 'List', snippetIds: ['list-bullet', 'list-numbered'] },
    { id: 'math', label: 'Math', icon: 'Sigma', snippetIds: ['math-inline', 'math-block'] },
    'underline',
    'code-block',
    'blockquote',
    'table',
    'comment',
    'hr',
    'footnote',
    'label',
    'ref',
  ],
}
